In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf

In [2]:
dataset=pd.read_csv(r'C:\Users\vibho\Documents\Deep Learning\emails.csv')
dataset.head()

Email No.  the  to  ect  and  for  of    a  you  hou  ...  connevey  jay  \
0   Email 1    0   0    1    0    0   0    2    0    0  ...         0    0   
1   Email 2    8  13   24    6    6   2  102    1   27  ...         0    0   
2   Email 3    0   0    1    0    0   0    8    0    0  ...         0    0   
3   Email 4    0   5   22    0    5   1   51    2   10  ...         0    0   
4   Email 5    7   6   17    1    5   2   57    0    9  ...         0    0   

   valued  lay  infrastructure  military  allowing  ff  dry  Prediction  
0       0    0               0         0         0   0    0           0  
1       0    0               0         0         0   1    0           0  
2       0    0               0         0         0   0    0           0  
3       0    0               0         0         0   0    0           0  
4       0    0               0         0         0   1    0           0  

[5 rows x 3002 columns]

In [5]:
dataset.isna().values

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

In [6]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5172 entries, 0 to 5171
Columns: 3002 entries, Email No. to Prediction
dtypes: int64(3001), object(1)
memory usage: 118.5+ MB


In [8]:
dataset.isna().sum()

Email No.     0
the           0
to            0
ect           0
and           0
             ..
military      0
allowing      0
ff            0
dry           0
Prediction    0
Length: 3002, dtype: int64

In [9]:
x=dataset.iloc[:, 1:-1].values
y=dataset.iloc[:, -1].values

In [10]:
print(y)

[0 0 0 ... 1 1 0]


In [11]:
print(x)

[[ 0  0  1 ...  0  0  0]
 [ 8 13 24 ...  0  1  0]
 [ 0  0  1 ...  0  0  0]
 ...
 [ 0  0  1 ...  0  0  0]
 [ 2  7  1 ...  0  1  0]
 [22 24  5 ...  0  0  0]]


In [12]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y, test_size=0.25, random_state=0)
print(x_train)
print(x_test)

[[32 25 14 ...  0  1  0]
 [42 19  1 ...  0  3  0]
 [ 1  3  1 ...  0  0  0]
 ...
 [12 18  8 ...  0  2  0]
 [10  6 96 ...  0  1  0]
 [ 1  8  2 ...  0  0  0]]
[[14  7  2 ...  0  0  0]
 [ 6  2  1 ...  0  0  0]
 [40  6  4 ...  0  1  0]
 ...
 [ 3  1  1 ...  0  0  0]
 [ 8  3 12 ...  0  0  0]
 [ 1  6  2 ...  0  2  0]]


In [13]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [14]:
print(x_train)

[[ 2.17234981  1.9271617   0.60399561 ... -0.05798835  0.02459753
  -0.07126366]
 [ 3.02915007  1.30898893 -0.28953232 ... -0.05798835  0.77294125
  -0.07126366]
 [-0.48373101 -0.33947178 -0.28953232 ... -0.05798835 -0.34957433
  -0.07126366]
 ...
 [ 0.45874928  1.20596014  0.1915981  ... -0.05798835  0.39876939
  -0.07126366]
 [ 0.28738923 -0.03038539  6.2400949  ... -0.05798835  0.02459753
  -0.07126366]
 [-0.48373101  0.1756722  -0.22079941 ... -0.05798835 -0.34957433
  -0.07126366]]


In [23]:
ann=tf.keras.models.Sequential()

In [29]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

In [30]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

In [31]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

In [32]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

In [33]:
ann.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))

In [34]:
ann.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [35]:
ann.fit(x_train,y_train,batch_size=32,epochs=100)

Epoch 1/100
122/122 [==============================] - 2s 2ms/step - loss: 0.6049 - accuracy: 0.7071
Epoch 2/100
122/122 [==============================] - 0s 2ms/step - loss: 0.4085 - accuracy: 0.7071
Epoch 3/100
122/122 [==============================] - 0s 2ms/step - loss: 0.2124 - accuracy: 0.9523
Epoch 4/100
122/122 [==============================] - 0s 2ms/step - loss: 0.0999 - accuracy: 0.9863
Epoch 5/100
122/122 [==============================] - 0s 2ms/step - loss: 0.0537 - accuracy: 0.9894
Epoch 6/100
122/122 [==============================] - 0s 2ms/step - loss: 0.0437 - accuracy: 0.9889
Epoch 7/100
122/122 [==============================] - 0s 2ms/step - loss: 0.0430 - accuracy: 0.9889
Epoch 8/100
122/122 [==============================] - 0s 2ms/step - loss: 0.0239 - accuracy: 0.9943
Epoch 9/100
122/122 [==============================] - 0s 2ms/step - loss: 0.0198 - accuracy: 0.9959
Epoch 10/100
122/122 [==============================] - 0s 2ms/step - loss: 0.0368 - accura

In [37]:
y_pred = ann.predict(x_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

41/41 [==============================] - 0s 2ms/step
[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [1 1]]


In [38]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[895  34]
 [  4 360]]


0.9706109822119103